### ISSUE TITLE
取消的时候怎么才能不让他动呢？？？大神

### ISSUE THREAD

**Issue by Invoker1024** [IFmiss/dialog#1]

**Comment by IFmiss** [comment]
可否描述的具体一点？

**Comment by AnglerDW** [comment]
可否描述的具体一点？

**Comment by Invoker1024** [comment]
弹出框出现之后，点击确定或取消，右侧纵向滚动条那个地方，整个页面会往左去一下，然后回来，看起来后面的整体背景抖动了一下。

**Comment by AnglerDW** [comment]
好了 已经更新好了,你可以更新一下试试。
我的目的是当有滚动条的时候，显示浮层的话，我用隐藏滚动条的方式，并设置body的 margin-right 让其占用滚动条的位置，从而达到元素不会移动的效果
我加了一个判断，当有滚动条的时候执行，没有则不执行那个方法
另外删除一个closeScroll方法  因为会影响关闭时 scroll的显示样式
